manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: george-norton
      url-base: https://github.com/george-norton
    - name: sphynx-owner
      url-base: https://github.com/sphynx-owner
  projects:
    - name: zmk
      remote: petejohanson
      revision: feat/pointers-move-scroll-ptp
      import: app/west.yml
    - name: maxtouch-zephyr-module
      remote: george-norton
      revision: main
    - name: ZMK_ps2_mouse_trackpoint_driver
      remote: sphynx-owner
      revision: main
  self:
    path: config
    import: deps.yml
