manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: george-norton
      url-base: https://github.com/george-norton
  projects:
    - name: zmk
      remote: petejohanson
      revision: 73c0fdc6bf0d7777699686dd21d9bd2fd117c0e3
      import: app/west.yml
    - name: maxtouch-zephyr-module
      remote: george-norton
      revision: main
  self:
    path: config
    import: deps.yml
